// <auto-generated />
namespace Buttler.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SimpleMembership : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SimpleMembership));
        
        string IMigrationMetadata.Id
        {
            get { return "201302111758452_SimpleMembership"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
